# Use Docker-based container (instead of OpenVZ)
sudo: false
language: scala
scala:
- 2.12.6
jdk:
- oraclejdk8

# codecov
script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.6/0.3.6 && chmod +x ~/bin/mill
  # - mill bloop.integrations.mill.Bloop/install
  - mill -i all __.compile
  - mill -i all __.test



# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.mill/ammonite/cache/
    - $HOME/.coursier/cache/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  # - find $HOME/.coursier/cache -name "*.lock" -type f -delete
