name: scala CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with mill
      run: |
        ./mill all __.compile
        ./mill all __.test
        ./mill jvmRoot.docs
        ./mill mantle.runMain "provingground.interface.Site"
